// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/uuid/UUID.d.ts
declare module 'uuid'{
    export function v1():string;
    export function v4():string;
}