// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/usage/usage.d.ts
declare module "usage" {

  export interface ResultObject {
    memory:number;
    memoryInfo: {
      rss:number;
      vsize:number;
    }
    cpu:number;
  }

  export interface Options {
    keepHistory:boolean;
  }

  export function lookup(pid:number, callback:(err:Error, result:ResultObject) => void):void;
  export function lookup(pid:number, options:Options, callback:(err:Error, result:ResultObject) => void):void;

  //Only availible on linux
  export function clearHistory(pid?:number):void;


}